name: ci-go
on:
  push:
    branches: [develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./basics
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'
          cache: false

      - name: Build
        run: go build ./...
      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test -v ./...