name: ci-go
on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'
          cache: false
      - name: Build
        run: go build ./...
      - name: Vet
        run: go vet ./...
      - name: Test (coverage)
        run: go test -covermode=atomic -coverprofile=coverage.out ./...
      - name: Coverage summary
        run: |
          if [ -f coverage.out ]; then
            go tool cover -func=coverage.out | tail -n1
            go tool cover -html=coverage.out -o coverage.html
          else
            echo "No coverage.out generated"
          fi
      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            coverage.out
            coverage.html
          if-no-files-found: ignore
